fix: update type error
saigon-technology/rn-base-project-typescript pull request #1
Opened 2022-12-30 07:34 UTC by vunguyendhSTS

2023-02-09 08:30 UTC, ngochuyduong requested changes

2023-02-09 08:30 UTC, ngochuyduong commented on template/src/store/reducers/app.ts
>        state: state.appState = action.payload
Reduce unnecessary state prop with ES6 syntax

2023-02-09 08:30 UTC, ngochuyduong commented on template/src/store/reducers/app.ts
>        state: state.showGlobalIndicator = action.payload
Reduce unnecessary state prop with ES6 syntax

2023-02-10 09:41 UTC, vunguyendhSTS commented
This PR combine on #10 PR so i close this PR

2023-02-10 09:41 UTC, vunguyendhSTS commented
This PR combine on #10 PR so i close this PR

2023-02-10 09:41 UTC, closed without merging