feat: mmkv storage
saigon-technology/rn-base-project-typescript pull request #12
Opened 2023-02-10 03:29 UTC by anhle10051996

2023-02-10 04:38 UTC, ngochuyduong requested changes

2023-02-10 04:38 UTC, ngochuyduong commented on template/App.tsx
>  interface TextWithDefaultProps extends Text {
Should move interface to common interface folder

2023-02-13 10:56 UTC, loc-nguyenthien requested changes
Should remove unrelated code from PR #7

2023-02-27 09:23 UTC, ThinhKimVo commented on template/App.tsx
> +;(Text as unknown as TextWithDefaultProps).defaultProps =
check format again

2023-02-27 09:23 UTC, ThinhKimVo commented on template/App.tsx
> +;(Text as unknown as TextWithDefaultProps).defaultProps =
why using `unknown`?

2023-02-27 09:23 UTC, ThinhKimVo commented on template/src/services/mmkv/storage.ts
> +import {storage} from '.'
shouldn't `import from '.'`

2023-02-27 09:25 UTC, ThinhKimVo commented on template/src/utilities/utils.ts
> +  return typeof val === 'object' && val?.constructor !== FormData && val !== null
please check error Type "Property 'constructor' does not exist on type 'NonNullable<T>'"

2023-03-07 04:18 UTC, closed without merging