feat: Debug menu and fix bugs
saigon-technology/rn-base-project-typescript pull request #13
Opened 2023-02-17 05:59 UTC by ThinhKimVo

2023-02-23 03:26 UTC, loc-nguyenthien requested changes

2023-02-23 03:26 UTC, loc-nguyenthien commented on template/src/components/DebugMenu.tsx
> +          <InfoMenuRow style={styles.infoMenu} title={title} description={description} />
Missing `key` prop

2023-02-23 03:26 UTC, loc-nguyenthien commented on template/src/components/DebugMenu.tsx
> +  const snapPoints = useMemo(() => ['95%'], [])
Move this to a constants outside of component, so we don't have to use `useMemo`

2023-02-23 03:26 UTC, loc-nguyenthien commented on template/src/components/DebugMenu.tsx
> +                : {color: colors.black, fontWeight: 'normal'},
Should avoid in-line styles

2023-02-23 03:26 UTC, loc-nguyenthien commented on template/src/components/InfoMenu.tsx
> +    <Text style={[{color: colors.gray}, descriptionStyle]}>{description}</Text>
avoid in-line styles

2023-02-27 10:14 UTC, loc-nguyenthien approved these changes

2023-03-03 07:03 UTC, hangnguyensaigontech approved these changes

2023-03-03 07:09 UTC, anhle10051996 approved these changes

2023-03-03 07:12 UTC, loido approved these changes

2023-03-03 08:07 UTC, merged