feat: update metrics type return the value has been passed to the function
saigon-technology/rn-base-project-typescript pull request #161
Opened 2023-08-03 07:04 UTC by baonguyenhsts

2023-08-04 08:09 UTC, hangnguyensaigontech approved these changes

2023-08-14 10:00 UTC, honghoangsts requested changes

2023-08-14 10:00 UTC, honghoangsts commented on template/src/themes/metrics.ts
> -const metrics: IMetrics = {
Do we need delete IMetrics?

2023-08-14 10:02 UTC, loc-nguyenthien approved these changes

2023-08-14 10:02 UTC, baonguyenhsts commented on template/src/themes/metrics.ts
> -const metrics: IMetrics = {
Yes because the IMetrics return number, not return the value we pass to the responsive function. I have added `as const` to metrics so it will autocomplete when we use it.

2023-08-14 10:03 UTC, honghoangsts commented on template/src/themes/metrics.ts
> -const metrics: IMetrics = {
I mean We need remove declare type IMetrics because not using it anymore

2023-08-14 10:10 UTC, huydosgtech approved these changes

2023-08-14 10:11 UTC, honghoangsts approved these changes

2023-08-14 10:11 UTC, merged