fix: missing config android env
saigon-technology/rn-base-project-typescript pull request #194
Opened 2023-11-10 08:12 UTC by chungnguyenhoang

2023-11-10 08:14 UTC, loc-nguyenthien approved these changes

2023-11-11 07:00 UTC, hangnguyensaigontech approved these changes

2023-12-22 08:30 UTC, loc-nguyenthien requested changes

2023-12-22 08:30 UTC, loc-nguyenthien commented on template/android/app/build.gradle
> +        resValue "string", "build_config_package", "com.saigontechnology.rnbaseprojecttypescript"
Change this using ENV like `applicationId`

2023-12-29 03:06 UTC, loido approved these changes

2023-12-29 03:11 UTC, ngochuyduong approved these changes

2023-12-29 03:30 UTC, baonguyenhsts approved these changes

2023-12-29 03:31 UTC, loc-nguyenthien approved these changes

2023-12-29 03:31 UTC, merged