feat: add redux persist configuration for store
saigon-technology/rn-base-project-typescript pull request #2
Opened 2023-01-05 14:18 UTC by huydosgtech

2023-02-09 08:55 UTC, ngochuyduong requested changes

2023-02-09 08:55 UTC, ngochuyduong commented on template/src/store/reducers/index.ts
> +import AsyncStorage from '@react-native-async-storage/async-storage'
Should use MMKVStorage

2023-02-14 02:12 UTC, loc-nguyenthien commented on template/src/store/reducers/index.ts
> +import AsyncStorage from '@react-native-async-storage/async-storage'
Since we have another PR for adding MMKV Storage, I think we can skip this here and complete it in #12

2023-02-14 02:36 UTC, loc-nguyenthien approved these changes

2023-02-17 01:59 UTC, ngochuyduong commented on template/src/store/reducers/index.ts
> +import AsyncStorage from '@react-native-async-storage/async-storage'
OK

2023-02-17 02:00 UTC, ngochuyduong approved these changes

2023-02-17 06:35 UTC, merged