feat: config github action
saigon-technology/rn-base-project-typescript pull request #5
Opened 2023-01-17 02:41 UTC by anhle10051996

2023-02-09 09:16 UTC, ngochuyduong requested changes
Missing pull-request config file, CODEOWNERS, dependabot config file

2023-02-13 10:38 UTC, loc-nguyenthien approved these changes

2023-02-23 06:22 UTC, ngochuyduong approved these changes

2023-02-24 08:53 UTC, tuledu approved these changes

2023-02-24 08:55 UTC, merged