feat: generate font and image script
saigon-technology/rn-base-project-typescript pull request #6
Opened 2023-01-18 00:51 UTC by anhle10051996

2023-02-14 02:48 UTC, loc-nguyenthien requested changes
@anhle10051996 I think we still need more configuration for new fonts to be usable, for example:
- Creating a file `react-native.config.js`
- link the font after adding

Please check these configs as well

2023-02-14 02:52 UTC, ngochuyduong approved these changes

2023-02-14 06:30 UTC, anhle10051996 commented
> @anhle10051996 I think we still need more configuration for new fonts to be usable, for example:
> 
> * Creating a file `react-native.config.js`
> * link the font after adding
> 
> Please check these configs as well

Hi @loc-nguyenthien, i already remove the default font. The purpose of this PR is just create the file export custom font that user adding, not setup new font. Different projects use different fonts so i didn't setup it, so it not create more effort to erase the default fonts from project

2023-02-16 02:43 UTC, loc-nguyenthien commented
> > @anhle10051996 I think we still need more configuration for new fonts to be usable, for example:
> > 
> > * Creating a file `react-native.config.js`
> > * link the font after adding
> > 
> > Please check these configs as well
> 
> Hi @loc-nguyenthien, i already remove the default font. The purpose of this PR is just create the file export custom font that user adding, not setup new font. Different projects use different fonts so i didn't setup it, so it not create more effort to erase the default fonts from project

Yeah I understand, but since we are generating the fonts user adding to the project. I think we can configure for using those fonts and auto run command to link those fonts, after all they are generated (with your code), so that user don't have to configure them again after they are generated.

2023-03-07 07:02 UTC, loc-nguyenthien approved these changes

2023-03-07 08:06 UTC, baonguyenhsts approved these changes

2023-03-08 04:47 UTC, merged