feat: add read me
saigon-technology/rn-base-project-typescript pull request #74
Opened 2023-04-04 07:08 UTC by hangnguyensaigontech

2023-04-05 02:53 UTC, ngochuyduong requested changes

2023-04-05 02:53 UTC, ngochuyduong commented on README.md
> +[![React Native Base Typescript STS License](https://img.shields.io/github/license/saigon-technology/rn-base-project-typescript)](https://choosealicense.com/licenses/mit/)
Change to https://img.shields.io/github/license/saigontechnology. Since we already moved to new repo

2023-04-05 11:00 UTC, hangnguyensaigontech commented on README.md
> +[![React Native Base Typescript STS License](https://img.shields.io/github/license/saigon-technology/rn-base-project-typescript)](https://choosealicense.com/licenses/mit/)
updated

2023-04-06 06:09 UTC, ngochuyduong approved these changes

2023-04-07 06:26 UTC, TranQuangPhi approved these changes

2023-04-07 06:38 UTC, merged